#!/bin/bash

echo "📧 Zoho SMTP Configuration Helper"
echo ""
echo "This script will help you configure Zoho SMTP for Supabase."
echo ""
echo "You'll need:"
echo "  1. Your Zoho email address"
echo "  2. Your Zoho App Password (not regular password)"
echo ""
echo "To get App Password:"
echo "  - Go to https://accounts.zoho.com"
echo "  - Security → App Passwords"
echo "  - Generate New App Password"
echo ""
read -p "Press Enter to continue or Ctrl+C to cancel..."

echo ""
echo "Enter your Zoho email address:"
read -p "Email: " ZOHO_EMAIL

echo ""
echo "Enter your Zoho App Password:"
read -p "App Password: " ZOHO_PASSWORD

echo ""
echo "Enter sender name (default: Weedhead Beats):"
read -p "Sender Name [Weedhead Beats]: " SENDER_NAME
SENDER_NAME=${SENDER_NAME:-Weedhead Beats}

echo ""
echo "=========================================="
echo "Environment Variables to Add:"
echo "=========================================="
echo ""
echo "SMTP_ADMIN_EMAIL=${ZOHO_EMAIL}"
echo "SMTP_HOST=smtp.zoho.com"
echo "SMTP_PORT=587"
echo "SMTP_USER=${ZOHO_EMAIL}"
echo "SMTP_PASS=${ZOHO_PASSWORD}"
echo "SMTP_SENDER_NAME=${SENDER_NAME}"
echo ""
echo "=========================================="
echo ""
echo "Where to add these:"
echo ""
echo "1. If Supabase is in Coolify:"
echo "   - Go to Coolify → Your Supabase Service → Environment Variables"
echo "   - Add each variable above"
echo ""
echo "2. If Supabase is self-hosted (Docker):"
echo "   - Add to your Supabase .env file"
echo "   - Or add to docker-compose.yml under environment:"
echo ""
echo "3. If Supabase Cloud:"
echo "   - Go to Dashboard → Settings → Auth → SMTP Settings"
echo "   - Enable Custom SMTP"
echo "   - Fill in the form with:"
echo "     Host: smtp.zoho.com"
echo "     Port: 587"
echo "     Username: ${ZOHO_EMAIL}"
echo "     Password: ${ZOHO_PASSWORD}"
echo "     Sender email: ${ZOHO_EMAIL}"
echo "     Sender name: ${SENDER_NAME}"
echo ""
echo "=========================================="
echo ""
echo "✅ Configuration ready!"
echo "Copy the variables above and add them to your Supabase configuration."
echo ""



